// All countries with ISO3 codes for comprehensive world population coverage
export const TOP_20_COUNTRIES = [
  // Top 50 most populous
  { code: 'CHN', name: 'China' },
  { code: 'IND', name: 'India' },
  { code: 'USA', name: 'United States' },
  { code: 'IDN', name: 'Indonesia' },
  { code: 'PAK', name: 'Pakistan' },
  { code: 'BRA', name: 'Brazil' },
  { code: 'NGA', name: 'Nigeria' },
  { code: 'BGD', name: 'Bangladesh' },
  { code: 'RUS', name: 'Russia' },
  { code: 'MEX', name: 'Mexico' },
  { code: 'JPN', name: 'Japan' },
  { code: 'ETH', name: 'Ethiopia' },
  { code: 'PHL', name: 'Philippines' },
  { code: 'EGY', name: 'Egypt' },
  { code: 'VNM', name: 'Vietnam' },
  { code: 'COD', name: 'DR Congo' },
  { code: 'TUR', name: 'Turkey' },
  { code: 'IRN', name: 'Iran' },
  { code: 'DEU', name: 'Germany' },
  { code: 'THA', name: 'Thailand' },
  { code: 'GBR', name: 'United Kingdom' },
  { code: 'FRA', name: 'France' },
  { code: 'ITA', name: 'Italy' },
  { code: 'TZA', name: 'Tanzania' },
  { code: 'ZAF', name: 'South Africa' },
  { code: 'MMR', name: 'Myanmar' },
  { code: 'KOR', name: 'South Korea' },
  { code: 'COL', name: 'Colombia' },
  { code: 'ESP', name: 'Spain' },
  { code: 'KEN', name: 'Kenya' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'DZA', name: 'Algeria' },
  { code: 'SDN', name: 'Sudan' },
  { code: 'UGA', name: 'Uganda' },
  { code: 'UKR', name: 'Ukraine' },
  { code: 'IRQ', name: 'Iraq' },
  { code: 'CAN', name: 'Canada' },
  { code: 'POL', name: 'Poland' },
  { code: 'MAR', name: 'Morocco' },
  { code: 'SAU', name: 'Saudi Arabia' },
  { code: 'AFG', name: 'Afghanistan' },
  { code: 'PER', name: 'Peru' },
  { code: 'MYS', name: 'Malaysia' },
  { code: 'AGO', name: 'Angola' },
  { code: 'MOZ', name: 'Mozambique' },
  { code: 'GHA', name: 'Ghana' },
  { code: 'YEM', name: 'Yemen' },
  { code: 'NPL', name: 'Nepal' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'MDG', name: 'Madagascar' },

  // Additional countries (51-150)
  { code: 'AUS', name: 'Australia' },
  { code: 'PRK', name: 'North Korea' },
  { code: 'CMR', name: 'Cameroon' },
  { code: 'NER', name: 'Niger' },
  { code: 'LKA', name: 'Sri Lanka' },
  { code: 'BFA', name: 'Burkina Faso' },
  { code: 'MLI', name: 'Mali' },
  { code: 'CHL', name: 'Chile' },
  { code: 'KAZ', name: 'Kazakhstan' },
  { code: 'MWI', name: 'Malawi' },
  { code: 'NLD', name: 'Netherlands' },
  { code: 'ECU', name: 'Ecuador' },
  { code: 'SYR', name: 'Syria' },
  { code: 'GTM', name: 'Guatemala' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'ZMB', name: 'Zambia' },
  { code: 'ZWE', name: 'Zimbabwe' },
  { code: 'RWA', name: 'Rwanda' },
  { code: 'SOM', name: 'Somalia' },
  { code: 'TCD', name: 'Chad' },
  { code: 'TUN', name: 'Tunisia' },
  { code: 'BEL', name: 'Belgium' },
  { code: 'BOL', name: 'Bolivia' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'HTI', name: 'Haiti' },
  { code: 'DOM', name: 'Dominican Republic' },
  { code: 'CZE', name: 'Czech Republic' },
  { code: 'GRC', name: 'Greece' },
  { code: 'PRT', name: 'Portugal' },
  { code: 'AZE', name: 'Azerbaijan' },
  { code: 'SWE', name: 'Sweden' },
  { code: 'HUN', name: 'Hungary' },
  { code: 'BLR', name: 'Belarus' },
  { code: 'TJK', name: 'Tajikistan' },
  { code: 'AUT', name: 'Austria' },
  { code: 'CHE', name: 'Switzerland' },
  { code: 'ISR', name: 'Israel' },
  { code: 'PNG', name: 'Papua New Guinea' },
  { code: 'TGO', name: 'Togo' },
  { code: 'SLE', name: 'Sierra Leone' },
  { code: 'LBY', name: 'Libya' },
  { code: 'LBN', name: 'Lebanon' },
  { code: 'NIC', name: 'Nicaragua' },
  { code: 'KGZ', name: 'Kyrgyzstan' },
  { code: 'PRY', name: 'Paraguay' },
  { code: 'LAO', name: 'Laos' },
  { code: 'BDI', name: 'Burundi' },
  { code: 'JOR', name: 'Jordan' },
  { code: 'ERI', name: 'Eritrea' },
  { code: 'CAF', name: 'Central African Republic' },
  { code: 'GEO', name: 'Georgia' },
  { code: 'DNK', name: 'Denmark' },
  { code: 'FIN', name: 'Finland' },
  { code: 'NOR', name: 'Norway' },
  { code: 'SVK', name: 'Slovakia' },
  { code: 'COG', name: 'Congo' },
  { code: 'CRI', name: 'Costa Rica' },
  { code: 'IRL', name: 'Ireland' },
  { code: 'NZL', name: 'New Zealand' },
  { code: 'LBR', name: 'Liberia' },
  { code: 'HRV', name: 'Croatia' },
  { code: 'PAN', name: 'Panama' },
  { code: 'MRT', name: 'Mauritania' },
  { code: 'URY', name: 'Uruguay' },
  { code: 'MNG', name: 'Mongolia' },
  { code: 'ARM', name: 'Armenia' },
  { code: 'ALB', name: 'Albania' },
  { code: 'LTU', name: 'Lithuania' },
  { code: 'JAM', name: 'Jamaica' },
  { code: 'QAT', name: 'Qatar' },
  { code: 'NAM', name: 'Namibia' },
  { code: 'BWA', name: 'Botswana' },
  { code: 'GMB', name: 'Gambia' },
  { code: 'GAB', name: 'Gabon' },
  { code: 'LSO', name: 'Lesotho' },
  { code: 'GNB', name: 'Guinea-Bissau' },
  { code: 'GNQ', name: 'Equatorial Guinea' },
  { code: 'TTO', name: 'Trinidad and Tobago' },
  { code: 'EST', name: 'Estonia' },
  { code: 'MUS', name: 'Mauritius' },
  { code: 'SWZ', name: 'Eswatini' },
  { code: 'TLS', name: 'Timor-Leste' },
  { code: 'CYP', name: 'Cyprus' },
  { code: 'FJI', name: 'Fiji' },
  { code: 'DJI', name: 'Djibouti' },
  { code: 'GUY', name: 'Guyana' },
  { code: 'COM', name: 'Comoros' },
  { code: 'BHR', name: 'Bahrain' },
  { code: 'SLV', name: 'El Salvador' },
  { code: 'HND', name: 'Honduras' },
  { code: 'ARE', name: 'United Arab Emirates' },
  { code: 'SGP', name: 'Singapore' },
  { code: 'KHM', name: 'Cambodia' },
  { code: 'OMN', name: 'Oman' },
  { code: 'KWT', name: 'Kuwait' },
  { code: 'LVA', name: 'Latvia' },
  { code: 'SRB', name: 'Serbia' },
  { code: 'BGR', name: 'Bulgaria' },
  { code: 'ROU', name: 'Romania' },
  { code: 'GIN', name: 'Guinea' },
  { code: 'BEN', name: 'Benin' },
  { code: 'UZB', name: 'Uzbekistan' },
  { code: 'TKM', name: 'Turkmenistan' },
  { code: 'SVN', name: 'Slovenia' },
  { code: 'LUX', name: 'Luxembourg' },
  { code: 'SUR', name: 'Suriname' },
  { code: 'CPV', name: 'Cape Verde' },
  { code: 'MLT', name: 'Malta' },
  { code: 'BRN', name: 'Brunei' },
  { code: 'BLZ', name: 'Belize' },
  { code: 'BTN', name: 'Bhutan' },
  { code: 'MDA', name: 'Moldova' },
  { code: 'MKD', name: 'North Macedonia' },
  { code: 'ISL', name: 'Iceland' },
  { code: 'BHS', name: 'Bahamas' },
  { code: 'MDV', name: 'Maldives' },
  { code: 'BRB', name: 'Barbados' },
  { code: 'NCL', name: 'New Caledonia' },
  { code: 'VUT', name: 'Vanuatu' },
  { code: 'SYC', name: 'Seychelles' },
  { code: 'STP', name: 'Sao Tome and Principe' },
  { code: 'WSM', name: 'Samoa' },
  { code: 'LCA', name: 'Saint Lucia' },
  { code: 'GRD', name: 'Grenada' },
  { code: 'TON', name: 'Tonga' },
  { code: 'KIR', name: 'Kiribati' },
  { code: 'FSM', name: 'Micronesia' },
  { code: 'AND', name: 'Andorra' },
  { code: 'DMA', name: 'Dominica' },
  { code: 'MNE', name: 'Montenegro' },
  { code: 'BIH', name: 'Bosnia and Herzegovina' },
  { code: 'PSE', name: 'Palestine' },
  { code: 'MNP', name: 'Northern Mariana Islands' },
];

// World Bank API configuration
export const WORLD_BANK_BASE_URL = 'https://api.worldbank.org/v2';

// Seconds in a year (365.25 days to account for leap years)
export const SECONDS_PER_YEAR = 31557600; // 365.25 * 24 * 60 * 60

// World Bank indicator codes
export const INDICATORS = {
  POPULATION: 'SP.POP.TOTL',
  BIRTH_RATE: 'SP.DYN.CBRT.IN',
  DEATH_RATE: 'SP.DYN.CDRT.IN',
  GROWTH_RATE: 'SP.POP.GROW'
} as const;
