// Country land border relationships
// This defines which countries share borders in real life
// Used to create topologically-correct cartogram

export const COUNTRY_NEIGHBORS: Record<string, string[]> = {
  // North America
  'USA': ['CAN', 'MEX'],
  'CAN': ['USA'],
  'MEX': ['USA', 'GTM', 'BLZ'],
  'GTM': ['MEX', 'BLZ', 'HND', 'SLV'],
  'BLZ': ['MEX', 'GTM'],
  'HND': ['GTM', 'SLV', 'NIC'],
  'SLV': ['GTM', 'HND'],
  'NIC': ['HND', 'CRI'],
  'CRI': ['NIC', 'PAN'],
  'PAN': ['CRI', 'COL'],

  // Caribbean (island nations - no land borders with others)
  'CUB': [],
  'HTI': ['DOM'],
  'DOM': ['HTI'],
  'JAM': [],
  'TTO': [],
  'BHS': [],
  'BRB': [],
  'LCA': [],
  'GRD': [],
  'DMA': [],

  // South America
  'COL': ['PAN', 'VEN', 'BRA', 'PER', 'ECU'],
  'VEN': ['COL', 'BRA', 'GUY'],
  'GUY': ['VEN', 'BRA', 'SUR'],
  'SUR': ['GUY', 'BRA'],
  'BRA': ['COL', 'VEN', 'GUY', 'SUR', 'PER', 'BOL', 'PRY', 'ARG', 'URY'],
  'ECU': ['COL', 'PER'],
  'PER': ['ECU', 'COL', 'BRA', 'BOL', 'CHL'],
  'BOL': ['PER', 'BRA', 'PRY', 'ARG', 'CHL'],
  'CHL': ['PER', 'BOL', 'ARG'],
  'ARG': ['CHL', 'BOL', 'PRY', 'BRA', 'URY'],
  'PRY': ['BOL', 'BRA', 'ARG'],
  'URY': ['BRA', 'ARG'],

  // Western Europe
  'ESP': ['PRT', 'FRA', 'AND'],
  'PRT': ['ESP'],
  'FRA': ['ESP', 'AND', 'BEL', 'LUX', 'DEU', 'CHE', 'ITA', 'MCO'],
  'AND': ['ESP', 'FRA'],
  'BEL': ['FRA', 'LUX', 'DEU', 'NLD'],
  'NLD': ['BEL', 'DEU'],
  'LUX': ['BEL', 'FRA', 'DEU'],
  'DEU': ['NLD', 'BEL', 'LUX', 'FRA', 'CHE', 'AUT', 'CZE', 'POL', 'DNK'],
  'CHE': ['FRA', 'DEU', 'AUT', 'ITA', 'LIE'],
  'ITA': ['FRA', 'CHE', 'AUT', 'SVN', 'SMR', 'VAT'],
  'DNK': ['DEU'],
  'IRL': [],
  'GBR': [],
  'ISL': [],
  'MLT': [],
  'MCO': ['FRA'],

  // Eastern Europe
  'POL': ['DEU', 'CZE', 'SVK', 'UKR', 'BLR', 'LTU'],
  'CZE': ['DEU', 'POL', 'SVK', 'AUT'],
  'SVK': ['POL', 'CZE', 'AUT', 'HUN', 'UKR'],
  'AUT': ['DEU', 'CZE', 'SVK', 'HUN', 'SVN', 'ITA', 'CHE', 'LIE'],
  'HUN': ['SVK', 'UKR', 'ROU', 'SRB', 'HRV', 'SVN', 'AUT'],
  'SVN': ['AUT', 'HUN', 'HRV', 'ITA'],
  'HRV': ['SVN', 'HUN', 'SRB', 'BIH'],
  'BIH': ['HRV', 'SRB', 'MNE'],
  'SRB': ['HUN', 'ROU', 'BGR', 'MKD', 'ALB', 'MNE', 'BIH', 'HRV'],
  'MNE': ['SRB', 'BIH', 'ALB'],
  'ALB': ['MNE', 'SRB', 'MKD', 'GRC'],
  'MKD': ['SRB', 'BGR', 'GRC', 'ALB'],
  'GRC': ['ALB', 'MKD', 'BGR', 'TUR'],
  'BGR': ['ROU', 'SRB', 'MKD', 'GRC', 'TUR'],
  'ROU': ['HUN', 'SRB', 'BGR', 'UKR', 'MDA'],
  'MDA': ['ROU', 'UKR'],
  'UKR': ['POL', 'SVK', 'HUN', 'ROU', 'MDA', 'RUS', 'BLR'],
  'BLR': ['POL', 'LTU', 'LVA', 'RUS', 'UKR'],
  'LTU': ['POL', 'BLR', 'LVA', 'RUS'],
  'LVA': ['LTU', 'BLR', 'RUS', 'EST'],
  'EST': ['LVA', 'RUS'],
  'RUS': ['NOR', 'FIN', 'EST', 'LVA', 'BLR', 'UKR', 'GEO', 'AZE', 'KAZ', 'CHN', 'MNG', 'PRK'],

  // Nordic
  'NOR': ['SWE', 'FIN', 'RUS'],
  'SWE': ['NOR', 'FIN'],
  'FIN': ['NOR', 'SWE', 'RUS'],

  // Caucasus & Central Asia
  'GEO': ['RUS', 'AZE', 'ARM', 'TUR'],
  'ARM': ['GEO', 'AZE', 'TUR', 'IRN'],
  'AZE': ['RUS', 'GEO', 'ARM', 'IRN', 'TUR'],
  'KAZ': ['RUS', 'CHN', 'KGZ', 'UZB', 'TKM'],
  'UZB': ['KAZ', 'KGZ', 'TJK', 'AFG', 'TKM'],
  'TKM': ['KAZ', 'UZB', 'AFG', 'IRN'],
  'KGZ': ['KAZ', 'CHN', 'TJK', 'UZB'],
  'TJK': ['KGZ', 'CHN', 'AFG', 'UZB'],

  // Middle East
  'TUR': ['GRC', 'BGR', 'GEO', 'ARM', 'AZE', 'IRN', 'IRQ', 'SYR'],
  'SYR': ['TUR', 'IRQ', 'JOR', 'ISR', 'LBN', 'PSE'],
  'LBN': ['SYR', 'ISR', 'PSE'],
  'ISR': ['LBN', 'SYR', 'JOR', 'EGY', 'PSE'],
  'PSE': ['ISR', 'EGY', 'JOR'],
  'JOR': ['SYR', 'IRQ', 'SAU', 'ISR', 'PSE'],
  'IRQ': ['TUR', 'SYR', 'JOR', 'SAU', 'KWT', 'IRN'],
  'IRN': ['TUR', 'ARM', 'AZE', 'TKM', 'AFG', 'PAK', 'IRQ'],
  'SAU': ['JOR', 'IRQ', 'KWT', 'QAT', 'ARE', 'OMN', 'YEM'],
  'KWT': ['IRQ', 'SAU'],
  'QAT': ['SAU'],
  'BHR': [],
  'ARE': ['SAU', 'OMN'],
  'OMN': ['SAU', 'ARE', 'YEM'],
  'YEM': ['SAU', 'OMN'],

  // South Asia
  'AFG': ['IRN', 'TKM', 'UZB', 'TJK', 'CHN', 'PAK'],
  'PAK': ['IRN', 'AFG', 'CHN', 'IND'],
  'IND': ['PAK', 'CHN', 'NPL', 'BTN', 'MMR', 'BGD'],
  'BGD': ['IND', 'MMR'],
  'NPL': ['CHN', 'IND'],
  'BTN': ['CHN', 'IND'],
  'LKA': [],
  'MDV': [],

  // East Asia
  'CHN': ['PRK', 'RUS', 'MNG', 'KAZ', 'KGZ', 'TJK', 'AFG', 'PAK', 'IND', 'NPL', 'BTN', 'MMR', 'LAO', 'VNM'],
  'MNG': ['RUS', 'CHN'],
  'PRK': ['CHN', 'RUS', 'KOR'],
  'KOR': ['PRK'],
  'JPN': [],

  // Southeast Asia
  'MMR': ['IND', 'BGD', 'CHN', 'LAO', 'THA'],
  'THA': ['MMR', 'LAO', 'KHM', 'MYS'],
  'LAO': ['CHN', 'MMR', 'THA', 'KHM', 'VNM'],
  'VNM': ['CHN', 'LAO', 'KHM'],
  'KHM': ['THA', 'LAO', 'VNM'],
  'MYS': ['THA', 'BRN', 'IDN'],
  'SGP': [],
  'BRN': ['MYS'],
  'IDN': ['MYS', 'PNG', 'TLS'],
  'TLS': ['IDN'],
  'PHL': [],

  // North Africa
  'MAR': ['DZA', 'ESH'],
  'DZA': ['MAR', 'TUN', 'LBY', 'NER', 'MLI', 'MRT'],
  'TUN': ['DZA', 'LBY'],
  'LBY': ['TUN', 'DZA', 'NER', 'TCD', 'SDN', 'EGY'],
  'EGY': ['LBY', 'SDN', 'ISR', 'PSE'],
  'MRT': ['DZA', 'MLI', 'SEN'],
  'MLI': ['DZA', 'MRT', 'SEN', 'GIN', 'CIV', 'BFA', 'NER'],
  'NER': ['DZA', 'LBY', 'TCD', 'NGA', 'BEN', 'BFA', 'MLI'],

  // West Africa
  'SEN': ['MRT', 'MLI', 'GIN', 'GMB'],
  'GMB': ['SEN'],
  'GNB': ['SEN', 'GIN'],
  'GIN': ['SEN', 'GNB', 'MLI', 'CIV', 'LBR', 'SLE'],
  'SLE': ['GIN', 'LBR'],
  'LBR': ['SLE', 'GIN', 'CIV'],
  'CIV': ['LBR', 'GIN', 'MLI', 'BFA', 'GHA'],
  'BFA': ['MLI', 'NER', 'BEN', 'TGO', 'GHA', 'CIV'],
  'GHA': ['CIV', 'BFA', 'TGO'],
  'TGO': ['GHA', 'BFA', 'BEN'],
  'BEN': ['TGO', 'BFA', 'NER', 'NGA'],
  'NGA': ['BEN', 'NER', 'TCD', 'CMR'],
  'CPV': [],

  // Central Africa
  'TCD': ['LBY', 'NER', 'NGA', 'CMR', 'CAF', 'SDN'],
  'CMR': ['NGA', 'TCD', 'CAF', 'COG', 'GAB', 'GNQ'],
  'CAF': ['TCD', 'CMR', 'COG', 'COD', 'SSD', 'SDN'],
  'GNQ': ['CMR', 'GAB'],
  'GAB': ['GNQ', 'CMR', 'COG'],
  'COG': ['GAB', 'CMR', 'CAF', 'COD', 'AGO'],
  'COD': ['COG', 'CAF', 'SSD', 'UGA', 'RWA', 'BDI', 'TZA', 'ZMB', 'AGO'],
  'STP': [],

  // East Africa
  'SDN': ['EGY', 'LBY', 'TCD', 'CAF', 'SSD', 'ETH', 'ERI'],
  'SSD': ['SDN', 'CAF', 'COD', 'UGA', 'KEN', 'ETH'],
  'ETH': ['SDN', 'SSD', 'KEN', 'SOM', 'DJI', 'ERI'],
  'ERI': ['SDN', 'ETH', 'DJI'],
  'DJI': ['ERI', 'ETH', 'SOM'],
  'SOM': ['ETH', 'DJI', 'KEN'],
  'KEN': ['SOM', 'ETH', 'SSD', 'UGA', 'TZA'],
  'UGA': ['SSD', 'COD', 'RWA', 'TZA', 'KEN'],
  'RWA': ['UGA', 'COD', 'BDI', 'TZA'],
  'BDI': ['RWA', 'COD', 'TZA'],
  'TZA': ['KEN', 'UGA', 'RWA', 'BDI', 'COD', 'ZMB', 'MWI', 'MOZ'],
  'SYC': [],
  'COM': [],
  'MUS': [],

  // Southern Africa
  'AGO': ['COG', 'COD', 'ZMB', 'NAM'],
  'ZMB': ['AGO', 'COD', 'TZA', 'MWI', 'MOZ', 'ZWE', 'BWA', 'NAM'],
  'MWI': ['TZA', 'ZMB', 'MOZ'],
  'MOZ': ['TZA', 'MWI', 'ZMB', 'ZWE', 'ZAF', 'SWZ'],
  'ZWE': ['ZMB', 'MOZ', 'ZAF', 'BWA'],
  'BWA': ['ZMB', 'NAM', 'ZAF', 'ZWE'],
  'NAM': ['AGO', 'ZMB', 'BWA', 'ZAF'],
  'ZAF': ['NAM', 'BWA', 'ZWE', 'MOZ', 'SWZ', 'LSO'],
  'SWZ': ['MOZ', 'ZAF'],
  'LSO': ['ZAF'],
  'MDG': [],

  // Oceania (mostly islands)
  'AUS': [],
  'NZL': [],
  'PNG': ['IDN'],
  'FJI': [],
  'NCL': [],
  'VUT': [],
  'WSM': [],
  'TON': [],
  'KIR': [],
  'FSM': [],
  'MNP': [],

  // Micro-states and special cases
  'LIE': ['CHE', 'AUT'],
  'SMR': ['ITA'],
  'VAT': ['ITA'],
  'ESH': ['MAR', 'DZA', 'MRT'],
  'CYP': [],
};

export function getCountryNeighbors(countryCode: string): string[] {
  return COUNTRY_NEIGHBORS[countryCode] || [];
}
