// Geographic positioning for cartogram
// Positions are relative (0-100 for x and y) to allow responsive scaling
// Based on approximate geographic locations

export interface CountryPosition {
  code: string;
  region: 'asia' | 'europe' | 'africa' | 'north-america' | 'south-america' | 'oceania' | 'caribbean';
  x: number; // 0-100 (left to right)
  y: number; // 0-100 (top to bottom)
  lat: number; // latitude
  lon: number; // longitude
}

export const COUNTRY_POSITIONS: CountryPosition[] = [
  // Asia (right side, middle)
  { code: 'CHN', region: 'asia', x: 75, y: 35 },
  { code: 'IND', region: 'asia', x: 68, y: 45 },
  { code: 'IDN', region: 'asia', x: 78, y: 58 },
  { code: 'PAK', region: 'asia', x: 64, y: 42 },
  { code: 'BGD', region: 'asia', x: 70, y: 45 },
  { code: 'JPN', region: 'asia', x: 85, y: 38 },
  { code: 'PHL', region: 'asia', x: 82, y: 50 },
  { code: 'VNM', region: 'asia', x: 76, y: 50 },
  { code: 'TUR', region: 'asia', x: 55, y: 38 },
  { code: 'IRN', region: 'asia', x: 60, y: 42 },
  { code: 'THA', region: 'asia', x: 74, y: 52 },
  { code: 'MMR', region: 'asia', x: 72, y: 48 },
  { code: 'KOR', region: 'asia', x: 82, y: 38 },
  { code: 'IRQ', region: 'asia', x: 58, y: 40 },
  { code: 'SAU', region: 'asia', x: 58, y: 46 },
  { code: 'AFG', region: 'asia', x: 63, y: 40 },
  { code: 'MYS', region: 'asia', x: 75, y: 55 },
  { code: 'YEM', region: 'asia', x: 58, y: 50 },
  { code: 'NPL', region: 'asia', x: 69, y: 43 },
  { code: 'PRK', region: 'asia', x: 83, y: 36 },
  { code: 'LKA', region: 'asia', x: 68, y: 52 },
  { code: 'KAZ', region: 'asia', x: 65, y: 32 },
  { code: 'SYR', region: 'asia', x: 56, y: 39 },
  { code: 'KHM', region: 'asia', x: 75, y: 51 },
  { code: 'JOR', region: 'asia', x: 56, y: 42 },
  { code: 'TJK', region: 'asia', x: 64, y: 38 },
  { code: 'AZE', region: 'asia', x: 58, y: 37 },
  { code: 'ARE', region: 'asia', x: 60, y: 46 },
  { code: 'ISR', region: 'asia', x: 55, y: 42 },
  { code: 'LBN', region: 'asia', x: 56, y: 40 },
  { code: 'LAO', region: 'asia', x: 75, y: 49 },
  { code: 'KGZ', region: 'asia', x: 66, y: 37 },
  { code: 'SGP', region: 'asia', x: 76, y: 56 },
  { code: 'OMN', region: 'asia', x: 61, y: 48 },
  { code: 'KWT', region: 'asia', x: 58, y: 44 },
  { code: 'ARM', region: 'asia', x: 57, y: 37 },
  { code: 'UZB', region: 'asia', x: 64, y: 37 },
  { code: 'TKM', region: 'asia', x: 62, y: 38 },
  { code: 'QAT', region: 'asia', x: 59, y: 46 },
  { code: 'BHR', region: 'asia', x: 59, y: 45 },
  { code: 'BTN', region: 'asia', x: 70, y: 44 },
  { code: 'MNG', region: 'asia', x: 74, y: 32 },
  { code: 'BRN', region: 'asia', x: 77, y: 55 },
  { code: 'TLS', region: 'asia', x: 82, y: 60 },
  { code: 'PSE', region: 'asia', x: 55, y: 42 },
  { code: 'MDV', region: 'asia', x: 66, y: 54 },

  // Europe (left-center)
  { code: 'RUS', region: 'europe', x: 60, y: 28 },
  { code: 'DEU', region: 'europe', x: 48, y: 32 },
  { code: 'GBR', region: 'europe', x: 45, y: 30 },
  { code: 'FRA', region: 'europe', x: 47, y: 34 },
  { code: 'ITA', region: 'europe', x: 49, y: 37 },
  { code: 'ESP', region: 'europe', x: 45, y: 37 },
  { code: 'UKR', region: 'europe', x: 53, y: 32 },
  { code: 'POL', region: 'europe', x: 50, y: 31 },
  { code: 'NLD', region: 'europe', x: 47, y: 31 },
  { code: 'BEL', region: 'europe', x: 47, y: 32 },
  { code: 'CZE', region: 'europe', x: 49, y: 32 },
  { code: 'GRC', region: 'europe', x: 51, y: 38 },
  { code: 'PRT', region: 'europe', x: 44, y: 38 },
  { code: 'SWE', region: 'europe', x: 50, y: 27 },
  { code: 'HUN', region: 'europe', x: 50, y: 33 },
  { code: 'BLR', region: 'europe', x: 52, y: 30 },
  { code: 'AUT', region: 'europe', x: 49, y: 33 },
  { code: 'CHE', region: 'europe', x: 48, y: 34 },
  { code: 'DNK', region: 'europe', x: 48, y: 30 },
  { code: 'FIN', region: 'europe', x: 52, y: 26 },
  { code: 'NOR', region: 'europe', x: 49, y: 26 },
  { code: 'SVK', region: 'europe', x: 50, y: 32 },
  { code: 'IRL', region: 'europe', x: 44, y: 30 },
  { code: 'HRV', region: 'europe', x: 49, y: 35 },
  { code: 'LTU', region: 'europe', x: 51, y: 29 },
  { code: 'LVA', region: 'europe', x: 51, y: 28 },
  { code: 'SRB', region: 'europe', x: 50, y: 35 },
  { code: 'BGR', region: 'europe', x: 51, y: 36 },
  { code: 'ROU', region: 'europe', x: 51, y: 34 },
  { code: 'SVN', region: 'europe', x: 49, y: 34 },
  { code: 'EST', region: 'europe', x: 51, y: 27 },
  { code: 'MDA', region: 'europe', x: 52, y: 33 },
  { code: 'MKD', region: 'europe', x: 50, y: 37 },
  { code: 'ALB', region: 'europe', x: 50, y: 38 },
  { code: 'ISL', region: 'europe', x: 42, y: 25 },
  { code: 'LUX', region: 'europe', x: 47, y: 32 },
  { code: 'MLT', region: 'europe', x: 49, y: 40 },
  { code: 'MNE', region: 'europe', x: 50, y: 36 },
  { code: 'CYP', region: 'europe', x: 54, y: 40 },
  { code: 'BIH', region: 'europe', x: 50, y: 35 },
  { code: 'GEO', region: 'europe', x: 57, y: 36 },
  { code: 'AND', region: 'europe', x: 46, y: 36 },

  // Africa (left-center, lower)
  { code: 'NGA', region: 'africa', x: 48, y: 52 },
  { code: 'ETH', region: 'africa', x: 56, y: 52 },
  { code: 'EGY', region: 'africa', x: 53, y: 44 },
  { code: 'COD', region: 'africa', x: 51, y: 58 },
  { code: 'TZA', region: 'africa', x: 54, y: 58 },
  { code: 'ZAF', region: 'africa', x: 52, y: 68 },
  { code: 'KEN', region: 'africa', x: 56, y: 56 },
  { code: 'DZA', region: 'africa', x: 48, y: 44 },
  { code: 'SDN', region: 'africa', x: 53, y: 50 },
  { code: 'UGA', region: 'africa', x: 54, y: 56 },
  { code: 'MAR', region: 'africa', x: 45, y: 42 },
  { code: 'AGO', region: 'africa', x: 50, y: 62 },
  { code: 'MOZ', region: 'africa', x: 55, y: 64 },
  { code: 'GHA', region: 'africa', x: 46, y: 52 },
  { code: 'MDG', region: 'africa', x: 58, y: 65 },
  { code: 'CMR', region: 'africa', x: 49, y: 54 },
  { code: 'NER', region: 'africa', x: 48, y: 50 },
  { code: 'BFA', region: 'africa', x: 46, y: 50 },
  { code: 'MLI', region: 'africa', x: 45, y: 48 },
  { code: 'MWI', region: 'africa', x: 55, y: 62 },
  { code: 'SEN', region: 'africa', x: 44, y: 50 },
  { code: 'ZMB', region: 'africa', x: 52, y: 63 },
  { code: 'ZWE', region: 'africa', x: 53, y: 65 },
  { code: 'RWA', region: 'africa', x: 53, y: 58 },
  { code: 'SOM', region: 'africa', x: 58, y: 54 },
  { code: 'TCD', region: 'africa', x: 50, y: 50 },
  { code: 'TUN', region: 'africa', x: 48, y: 41 },
  { code: 'GIN', region: 'africa', x: 45, y: 51 },
  { code: 'BEN', region: 'africa', x: 47, y: 52 },
  { code: 'TGO', region: 'africa', x: 46, y: 52 },
  { code: 'SLE', region: 'africa', x: 44, y: 52 },
  { code: 'LBY', region: 'africa', x: 50, y: 44 },
  { code: 'BDI', region: 'africa', x: 53, y: 58 },
  { code: 'ERI', region: 'africa', x: 57, y: 51 },
  { code: 'CAF', region: 'africa', x: 51, y: 54 },
  { code: 'COG', region: 'africa', x: 50, y: 58 },
  { code: 'LBR', region: 'africa', x: 45, y: 53 },
  { code: 'MRT', region: 'africa', x: 45, y: 47 },
  { code: 'NAM', region: 'africa', x: 51, y: 66 },
  { code: 'BWA', region: 'africa', x: 52, y: 66 },
  { code: 'GMB', region: 'africa', x: 44, y: 50 },
  { code: 'GAB', region: 'africa', x: 49, y: 58 },
  { code: 'LSO', region: 'africa', x: 52, y: 69 },
  { code: 'GNB', region: 'africa', x: 44, y: 51 },
  { code: 'GNQ', region: 'africa', x: 48, y: 56 },
  { code: 'SWZ', region: 'africa', x: 53, y: 68 },
  { code: 'DJI', region: 'africa', x: 58, y: 52 },
  { code: 'COM', region: 'africa', x: 57, y: 63 },
  { code: 'CPV', region: 'africa', x: 42, y: 49 },
  { code: 'STP', region: 'africa', x: 47, y: 56 },
  { code: 'SYC', region: 'africa', x: 60, y: 58 },
  { code: 'MUS', region: 'africa', x: 61, y: 66 },

  // North America (left side, middle-top)
  { code: 'USA', region: 'north-america', x: 20, y: 38 },
  { code: 'MEX', region: 'north-america', x: 18, y: 46 },
  { code: 'CAN', region: 'north-america', x: 22, y: 28 },
  { code: 'GTM', region: 'north-america', x: 17, y: 50 },
  { code: 'CUB', region: 'caribbean', x: 24, y: 48 },
  { code: 'HTI', region: 'caribbean', x: 26, y: 49 },
  { code: 'DOM', region: 'caribbean', x: 27, y: 49 },
  { code: 'HND', region: 'north-america', x: 18, y: 50 },
  { code: 'NIC', region: 'north-america', x: 19, y: 51 },
  { code: 'SLV', region: 'north-america', x: 17, y: 50 },
  { code: 'CRI', region: 'north-america', x: 19, y: 52 },
  { code: 'PAN', region: 'north-america', x: 23, y: 52 },
  { code: 'JAM', region: 'caribbean', x: 25, y: 49 },
  { code: 'TTO', region: 'caribbean', x: 28, y: 51 },
  { code: 'BHS', region: 'caribbean', x: 25, y: 47 },
  { code: 'BRB', region: 'caribbean', x: 28, y: 50 },
  { code: 'BLZ', region: 'north-america', x: 17, y: 49 },
  { code: 'LCA', region: 'caribbean', x: 28, y: 50 },
  { code: 'GRD', region: 'caribbean', x: 28, y: 51 },
  { code: 'DMA', region: 'caribbean', x: 28, y: 50 },

  // South America (left side, lower)
  { code: 'BRA', region: 'south-america', x: 30, y: 62 },
  { code: 'COL', region: 'south-america', x: 25, y: 55 },
  { code: 'ARG', region: 'south-america', x: 28, y: 72 },
  { code: 'PER', region: 'south-america', x: 24, y: 60 },
  { code: 'VEN', region: 'south-america', x: 27, y: 54 },
  { code: 'CHL', region: 'south-america', x: 26, y: 70 },
  { code: 'ECU', region: 'south-america', x: 23, y: 58 },
  { code: 'BOL', region: 'south-america', x: 27, y: 64 },
  { code: 'PRY', region: 'south-america', x: 29, y: 67 },
  { code: 'URY', region: 'south-america', x: 30, y: 71 },
  { code: 'GUY', region: 'south-america', x: 29, y: 54 },
  { code: 'SUR', region: 'south-america', x: 30, y: 55 },

  // Oceania (far right, bottom)
  { code: 'AUS', region: 'oceania', x: 85, y: 72 },
  { code: 'PNG', region: 'oceania', x: 88, y: 58 },
  { code: 'NZL', region: 'oceania', x: 92, y: 78 },
  { code: 'FJI', region: 'oceania', x: 95, y: 64 },
  { code: 'NCL', region: 'oceania', x: 91, y: 67 },
  { code: 'VUT', region: 'oceania', x: 92, y: 65 },
  { code: 'WSM', region: 'oceania', x: 98, y: 62 },
  { code: 'TON', region: 'oceania', x: 97, y: 66 },
  { code: 'KIR', region: 'oceania', x: 97, y: 56 },
  { code: 'FSM', region: 'oceania', x: 90, y: 53 },
  { code: 'MNP', region: 'oceania', x: 88, y: 50 },
];

export function getCountryPosition(countryCode: string): CountryPosition | undefined {
  return COUNTRY_POSITIONS.find(p => p.code === countryCode);
}
